[project]
name = "tornado-ping"
version = "0.3.6"
authors = [
    { name = "Mark Guagenti", email = "mgenti@gentiweb.com" },
]
description = "Tornado ping implementation"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ""
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Programming Language :: Python :: 2.7",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
"Homepage" = "https://github.com/mgenti/tornado-ping"
