[tool.poetry]
name = "ZTTT"
version = "0.3.0"
description = "A Tic Tac Toe Library with a near perfect engine"
readme = "README.rst"
authors = ["Sumanth NR <sumanthnr62@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
