[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pandas_gdc_agent"
version = "0.0.2"
authors = [
  { name="Paritosh Raj", email="paritosh@hasura.io" },
]
description = "Hasura GDC agent based on pandas."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "Flask==2.1.2",
    "pandas==1.4.3"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/paritosh-08/pandas_gdc_agent"
"Bug Tracker" = "https://github.com/paritosh-08/pandas_gdc_agent/issues"