[tool.poetry]
name = "cri-simulations"
version = "1.0"
description = "Software for interacting with the CRI neuromorphic hardware"
authors = ["Justin Frank"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = ">=1.18"
confuse = "^1.7.0"
click = "^8.1.3"
PyMetis = "^2020.1"
networkx = "^2.8.3"
matplotlib = "^3.5.2"
scipy = "^1.8.1"
k-means-constrained = "^0.7.1"
fbpca = "^1.0"
sklearn = "^0.0"
metis = "^0.2a5"
bidict = "^0.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
