[project]
name = "suriin"
version = "0.0.22"
description = "Suriin (soo-ree-ihn or sure-ree-in, depending on your pick) is a simple, lightweight, and minimalist Python library for general testing."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [ "Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
dependencies = [ "bleach == 5.0.1", "build == 0.8.0", "certifi == 2022.6.15", "cffi == 1.15.1", "charset-normalizer == 2.1.0", "commonmark == 0.9.1", "cryptography == 37.0.4", "docutils == 0.19", "idna == 3.3", "importlib-metadata == 4.12.0", "jeepney == 0.8.0", "keyring == 23.6.0", "packaging == 21.3", "pep517 == 0.12.0", "pkginfo == 1.8.3", "pycparser == 2.21", "Pygments == 2.12.0", "pyparsing == 3.0.9", "readme-renderer == 35.0", "requests == 2.28.1", "requests-toolbelt == 0.9.1", "rfc3986 == 2.0.0", "rich == 12.5.1", "SecretStorage == 3.3.2", "six == 1.16.0", "toml == 0.10.2", "tomli == 2.0.1", "twine == 4.0.1", "urllib3 == 1.26.10", "webencodings == 0.5.1", "zipp == 3.8.0",]
[[project.authors]]
name = "LJ. Sta. Ana"
email = "lvjhn.mx@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://gitlab.com/demo-package/demo-package-python"
"Bug Tracker" = "https://github.com/demo-package/demo-package-python/~/issues"
