[tool.poetry]
name = "s4sdk"
version = "0.1.1a1"
description = ""
authors = ["Roy Chotechuang <htraexd@gmail.com>"]

include = [
    "LICENSE",
]


[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.4.3"
PyYAML = "^6.0"
click = "^8.1.3"
argparse = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
