[tool.poetry]
name = "bagbag"
version = "0.4.2"
description = "An all in one python library"

license = "MIT"

authors = [
    "Darren"
]

readme = 'README.md'

repository = "https://github.com/darren2046/allinone_py_lib"

keywords = ['base', 'library']

exclude = [
  ".git",
  "ident",
  "publish.py",
  "__pycache__",
  ".github",
]

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.6.0"
redis = "^4.3.4"
orator = "^0.9.9"
PyMySQL = "^1.0.2"
telethon = "^1.24.0"

[build-system]
requires = ["poetry>=0.12a3"]
build-backend = "poetry.masonry.api"